### ISSUE TITLE
项目运行报错，.env.example可能不是最新的，部分变量没有了

### ISSUE THREAD

**Issue by 4466** [huijiewei/yii2-boilerplate#12]
兄弟，你的yii2-boilerplate中的.env.example不是最新的，改为.env，部分变量没有，导致npm run serve:admin，并不会进入到配置文件vue.entry.admin.config.js中，还是进入了webpack默认得配置的文件，应该是部分变量缺失了，所以报错了，报错如下：
This relative module was not found:

* ./src/main.js in multi (webpack)-dev-server/client?http://www.bp.test:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js, multi (webpack)/hot/dev-server.js (webpack)-dev-server/client?http://www.bp.test:8080&sockPath=/sockjs-node ./src/main.js

，能不能帮我看下，或者把最新的.env发给我下，或者更新下线上的.env.example，感激不尽，谢谢哈

**Comment by huijiewei** [comment]
.env.example 是PHP运行的环境文件。和前端无关

我已经更新了基础库和配置文件，可以正常运行
