### ISSUE TITLE
运行还是报错，没法正常npm run serve:admin

### ISSUE THREAD

**Issue by 4466** [huijiewei/yii2-boilerplate#13]
重新克隆了你今天更新的项目，重新全部按照你的安装步骤，依然没法运行成功，还是有一个错：
./src/main.js in multi (webpack)-dev-server/client?http://www.bp.test:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
npm run serve:admin关联的配置配置文件是vue.entry.admin.config.js，里面的端口号是8090，为什么还是8080，明显没有进入到这个文件哦，看了忽略的配置文件.gitignore里面有个webpack.entity.*.js，应该是webpack.entity的文件都被你忽略了，不知道是不是没有这类配置文件导致npm run的时候出错了，进不到vue.entry.admin.config.js这个配置文件里面，不知道你能够留个微信或者QQ啥的，请教你一下，兄弟，感激不尽。
我的微信：zilingwei

**Comment by huijiewei** [comment]
感谢你的反馈。我已经修复了在 Windows 下无法启动的问题。
