### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by ywhlhy** [huijiewei/yii2-boilerplate#6]
执行migrate的时候报错，报错信息如下：
 php bin/yii migrate --migrationPath=@vendor/huijiewei/yii2-wechat/src/migrations
Yii Migration Tool (based on Yii v2.0.35)

Total 1 new migration to be applied:
	m180612_023911_create_wechat_user_table

Apply the above migration? (yes|no) [no]:yes
*** applying m180612_023911_create_wechat_user_table
    > create table {{%wechat_user}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'accessTokenExpiredAt'
The SQL being executed was: CREATE TABLE `bp_wechat_user` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`appId` varchar(50) NOT NULL DEFAULT '',
	`openId` varchar(50) NOT NULL DEFAULT '',
	`unionId` varchar(50) NOT NULL DEFAULT '',
	`nickname` varchar(32) NOT NULL DEFAULT '',
	`avatar` varchar(200) NOT NULL DEFAULT '',
	`details` text NULL DEFAULT NULL,
	`accessToken` varchar(100) NOT NULL DEFAULT '',
	`refreshToken` varchar(100) NOT NULL DEFAULT '',
	`accessTokenExpiredAt` timestamp(0) NOT NULL DEFAULT 0,
	`refreshTokenExpiredAt` timestamp(0) NOT NULL DEFAULT 0,
	`createdAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ENGINE=InnoDB

**Comment by huijiewei** [comment]
这个是 wechat 扩展的错误，不影响使用。

我会更新这个扩展，兼容 MySQL 8+
