### ISSUE TITLE
后台无法访问

### ISSUE THREAD

**Issue by ywhlhy** [huijiewei/yii2-boilerplate#7]
前端编译通过之后，  提示下面正确信息：
  App running at:
  - Local:   http://www.bp.test:8090/
  - Network: http://www.bp.test:8090/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

按照提示，打开首页：http://www.bp.test:8090/，但是出现错误信息：Cannot GET /

**Comment by ywhlhy** [comment]
通过http://www.bp.test/admin/login?direct=%2Fhome访问打开后台页面，但是登陆却提示没啥账号，数据库一看，一个账号都没有，都是空的，估计是migrate那个步骤有问题。

**Comment by huijiewei** [comment]
修复了初始化脚本错误
